### ISSUE TITLE
Can you help me understand: where are technical and biological replicates distinguished?

### ISSUE THREAD

**Issue by tomsing1** [pachterlab/zika#1]
It is great to see that Sleuth can handle unusual designs, e.g. technical replication. Can you help me understand how the 

```
so <- sleuth_prep(s2c, ~ condition, target_mapping = t2g)
```
call [here](https://github.com/pachterlab/zika/blob/master/analyze_data.R#L36) instructs Sleuth that there are only two biological replicates per condition? I am having trouble figuring this out, because the `condition` column from the [design matrix](https://github.com/pachterlab/zika/blob/master/zikadesignmatrix.txt) doesn't indicate whether a sample is a technical or a biological replicate.

I also saw the number of fragments per library is used to calculate a weighted mean [here](https://github.com/pachterlab/zika/blob/master/R/measurement_error.R#L407) for estimating the bootstrap error. Does that also adjust the number of independent (biological) replicates to consider somehow?

Thanks in advance for any insights,
Thomas

**Comment by lynnyi** [comment]
Hi Thomas,

Apologies for late response. You are correct in that the given covariate does not distinguish biological and technical replicates, and thus, all samples are considered biological replicates. As such, there is likely an underestimate of total variance.  For a more "correct" model,  we considered adding the technical covariate into the design matrix (i.e. single v paired ends) and using a heteroscedastic model to allow for different variances between different techniques (the sleuth model as it stands now is homoscedastic), but decided that was beyond the scope for this project.


The weighted mean of the bootstrap error is to adjust for the difference in library sizes -- as you can see, the average library size of the single ended reads is ~10X the paired end, and we wanted to account for this effect on variance estimates.

Best,
Lynn

**Comment by tomsing1** [comment]
Great, thanks for the detailed explanation!
